version: '3'

services:
  # PostgreSQL
  database:
    container_name: wefin_database
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=wefin_pessoas